apiVersion: 1

datasources:
  - name: Smart City PostgreSQL
    uid: smart-city-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      database: smart_cities_db
      sslmode: disable
      postgresVersion: 15
      timescaledb: false
    isDefault: true
    editable: false
